project/main/forms.py
from flask_wtf import Form
from wtforms import StringField, DateField, IntegerField, SelectField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length, EqualTo, Email
import datetime

class RegisterQRForm(Form):

    panel_id=IntegerField('Panel ID', validators=[DataRequired()])
    end_user=StringField('End User', validators=[DataRequired()])
    panel_name=StringField('Panel Name', validators=[DataRequired()])



class AddCustomerForm(Form):
    customer_id=IntegerField()
    name=StringField('Customer Name', validators=[DataRequired()])

class RegisterForm(Form):
    name= StringField(
        'Username',
        validators=[DataRequired(), Length(min=6, max=30)]
    )
    email= StringField(
        'Email',
        validators=[DataRequired(), Email(), Length(min=6, max=40)]
    )
    password = PasswordField(
        'Password',
        validators=[DataRequired(), Length(min=6, max=40)])
    confirm= PasswordField(
        'Repeat Password',
        validators=[DataRequired(), EqualTo('password', message='Passwords must match')]
    )
    company = StringField(
        'Company',
        validators=[DataRequired(), Length(min=3, max=40)])
    

class LoginForm(Form):
    name=StringField(
        'Username',
        validators=[DataRequired()]
    )
    password=PasswordField(
        'Password',
        validators=[DataRequired()]
    )
   

class AddProjectForm(Form):
    project_id=IntegerField()
    name=StringField('Project Name', validators=[DataRequired()])

class AddPanelForm(Form):
    panel_id=IntegerField()
    name=StringField('Panel Name', validators=[DataRequired()])
 

class SendEmailLink(Form):
    email= StringField(
        'Email',
        validators=[DataRequired(), Email(), Length(min=6, max=40)])

class AddMaintenanceLog(Form):
    MaintenanceLog_id = IntegerField()
    MaintenanceLog_panel_id= IntegerField()
    maintenance_issue = StringField('Maintenance Issue', validators=[DataRequired()])
    priority = SelectField(
        'Priority',
        validators=[DataRequired()],
        choices=[
            ('1', '1'), ('2', '2'), ('3', '3')
        ]
    )
    status = IntegerField('Status')
    action_taken= StringField('Action Taken') # might have to get rid of validators since this can be nullable


class RequestResetForm(Form):
    email= StringField(
        'Email',
        validators=[DataRequired(), Email(), Length(min=6, max=40)])
   

class ResetPasswordForm(Form):
    password = PasswordField(
        'Password',
        validators=[DataRequired(), Length(min=6, max=40)])
    confirm= PasswordField(
        'Repeat Password',
        validators=[DataRequired(), EqualTo('password', message='Passwords must match')])
    submit=SubmitField('Reset Password')

project/main/views.py
#views
from .forms import AddCustomerForm, RegisterForm, LoginForm, AddProjectForm, AddPanelForm,RegisterQRForm, RequestResetForm, ResetPasswordForm, SendEmailLink, AddMaintenanceLog
import jwt
from time import time
from functools import wraps
from flask import Flask, flash, redirect, render_template, \
request, session, url_for, Response, Blueprint
from sqlalchemy.exc import IntegrityError
from flask_mail import Message, Mail
from project.models import Customer, User, Project, Panel, QRcode, Maintenance_Logs
from project import db, bcrypt , mail
import datetime
main_blueprint= Blueprint('main', __name__)

import boto3
import os
import datetime


####### 3/13 password reset
from flask_jwt_extended import jwt_required, create_access_token, get_jwt_identity
import flask_login
#######


S3_BUCKET=os.environ.get('S3_BUCKET')
s3=boto3.client('s3')

def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash('You need to login first.')
            return redirect(url_for('main.login'))
    return wrap

########################### Maintenance Logs ##############################################


@main_blueprint.route('/MaintenanceLogs/#<int:panel_id>/')
def MaintenanceLogs(panel_id):
    panel_id=panel_id
    open_logs=db.session.query(Maintenance_Logs).filter_by(status='1', MaintenanceLog_panel_id = panel_id).order_by(Maintenance_Logs.priority.desc())
    closed_logs=db.session.query(Maintenance_Logs).filter_by(status ='0',  MaintenanceLog_panel_id = panel_id).order_by(Maintenance_Logs.priority.desc())
    
    return render_template(
        'QR_dataview_logs.html',
        form=AddMaintenanceLog(request.form),
        open_logs=open_logs,
        closed_logs=closed_logs,
        panel_id=panel_id
    )
    
@main_blueprint.route('/NewMaintenanceLog/#<int:panel_id>/', methods=['GET','POST'])
def new_MaintenanceLog(panel_id):
    error=None
    panel_id=panel_id
    form=AddMaintenanceLog(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_MaintenanceLog=Maintenance_Logs(
            panel_id,
            form.maintenance_issue.data,
            datetime.datetime.utcnow(),
            form.priority.data,
            '1',
            None
            )
            db.session.add(new_MaintenanceLog)
            db.session.commit()
            flash('Maintenance log created successfully.')
    return redirect(url_for('main.MaintenanceLogs', panel_id=panel_id))
    
    
    


@main_blueprint.route('/complete/#<int:MaintenanceLog_id>/', methods=['GET','POST'])
def complete_MaintenanceLog(MaintenanceLog_id):
    error=None
    new_id=MaintenanceLog_id
    form=AddMaintenanceLog(request.form)
    maintenancelog=db.session.query(Maintenance_Logs).filter_by(MaintenanceLog_id=new_id).first()
    panel_id=maintenancelog.MaintenanceLog_panel_id
    if request.method=='POST':
        
        maintenancelog.status='0'
        maintenancelog.action_taken=f"{form.action_taken.data}"
        db.session.commit()
        flash('Maintenance log completed.')
        return redirect(url_for('main.MaintenanceLogs', panel_id=panel_id))

@main_blueprint.route('/deleteMaintenancelog/<int:MaintenanceLog_id>/')
def delete_MaintenanceLog(MaintenanceLog_id):
    new_id=MaintenanceLog_id
    maintenancelog=db.session.query(Maintenance_Logs).filter_by(MaintenanceLog_id=new_id).first()
    panel_id=maintenancelog.MaintenanceLog_panel_id
    db.session.query(Maintenance_Logs).filter_by(MaintenanceLog_id=new_id).delete()
    db.session.commit()
    flash('The maintenance log was deleted.')
    return redirect(url_for('main.MaintenanceLogs', panel_id=panel_id))



##########################################################################################################################################


#register QR code
@main_blueprint.route('/QRmain/<int:QR_id>', methods=['GET', 'POST'])
def QRmain(QR_id):
    QR_id=QR_id
    error=None
    form=RegisterQRForm(request.form)
    
    #checks if qr ID exists in the QR code table. If exists then it takes you to its data.
    qrcode=QRcode.query.filter_by(QR_id=QR_id).first()
    if qrcode is not None :
        panel_id=qrcode.panel_id #pulling panel ID from QRcode model
        return redirect(url_for('main.QRfiles',panel_id=panel_id))

    if request.method== 'POST':
        if form.validate_on_submit():
            PID=request.form['panel_id']
            panel=Panel.query.filter_by(panel_id=PID).first()
            
            ##checks if panel exists

            if panel is None:

                error= 'That panel does not exist'
                return render_template('QR_register.html', form=form, error=error)
            
            if panel is not None and panel.name == request.form['panel_name']: #and panel.panel_id == request.form['panel_id'] and panel.project_id == request.form['project_id']:
               
                
                new_QR= QRcode(
                form.panel_id.data,
                form.end_user.data,
                form.panel_name.data,
                QR_id
                )
                try:
                    db.session.add(new_QR)
                    db.session.commit()
                    flash('Thanks for registering QR code.')
                    return redirect(url_for('main.login')) #### change this to the QR URL
                except IntegrityError: #Verify integrity error works for other shit besides email
                    error= 'That panel ID has already been linked to a QR code.'
                    return render_template('QR_register.html', form=form, error=error)

            else:
                error= 'Panel name does not match. This field is case sensitive'
                return render_template('QR_register.html', form=form, error=error)
      
    return render_template('QR_register.html', form=form, error=error)

###use this to view files from emailed link
@main_blueprint.route('/QRlink/<int:panel_id>/')
def QRlink(panel_id):
    qrcode=QRcode.query.filter_by(panel_id=panel_id).first()
   
    panels=Panel.query.filter_by(panel_id=panel_id).first()
    panel_id=panels.panel_id
    PANEL_ID=str(panel_id)
    panel_name=panels.name

    s3_resource=boto3.resource('s3')
    my_bucket=s3_resource.Bucket(S3_BUCKET)
    summaries=my_bucket.objects.filter(Prefix=f'{PANEL_ID}/')
    
    
    return render_template('QR_dataview_Emailed.html', my_bucket=my_bucket, files=summaries, panel_id=panel_id, panel_name=panel_name, )


@main_blueprint.route('/QRfiles/#<int:panel_id>/')
def QRfiles(panel_id):
    qrcode=QRcode.query.filter_by(panel_id=panel_id).first()
    form=SendEmailLink(request.form)
    if qrcode is None: ##idk why i put this shit here
        
        return redirect(url_for('main.login'))
    
    

    panels=Panel.query.filter_by(panel_id=panel_id).first()
    panel_id=panels.panel_id
    PANEL_ID=str(panel_id)
    panel_name=panels.name

    s3_resource=boto3.resource('s3')
    my_bucket=s3_resource.Bucket(S3_BUCKET)
    summaries=my_bucket.objects.filter(Prefix=f'{PANEL_ID}/')
    
    
    return render_template('QR_dataview.html', my_bucket=my_bucket, files=summaries, panel_id=panel_id, panel_name=panel_name, form=form)
 

@main_blueprint.route('/QRemail/<int:panel_id>/', methods=['POST'])
def emailQRlink(panel_id):
    form=SendEmailLink(request.form)
    panels=Panel.query.filter_by(panel_id=panel_id).first()
    panel_name=panels.name
    if request.method== 'POST':
        if form.validate_on_submit():
            msg = Message(subject=f"Link to {panel_name} data ",
                        sender=("main@scanmatics.com"),
                        recipients=[request.form['email']]) 
            msg.body=f'''"https://gentle-refuge-43155.herokuapp.com/QRlink/{panel_id}/" '''
            mail.send(msg)
            flash('Email has been sent')
            return redirect(url_for('main.QRfiles', panel_id=panel_id))



    
#register customer
@main_blueprint.route('/register/', methods=['GET', 'POST'])
def register():
    error=None
    form=RegisterForm(request.form)
    if request.method== 'POST':
        if form.validate_on_submit():
            new_user= User(
                form.name.data,
                form.email.data,
                bcrypt.generate_password_hash(form.password.data).decode('utf-8'),####### added.decode(utf-8)
                form.company.data,
            )
            try:
                db.session.add(new_user)
                db.session.commit()
                flash('Thanks for registering. Please login.')
                return redirect(url_for('main.login'))
            except IntegrityError:
                error= 'That username and/or email already exists.'
                return render_template('register.html', form=form, error=error)
    return render_template('register.html', form=form, error=error)



@main_blueprint.route('/logout/')
def logout():
    session.pop('logged_in', None)
    session.pop('company_id', None)
    session.pop('name', None)
    flash('Adios!')
    return redirect(url_for('main.login'))

@main_blueprint.route('/', methods=['GET', 'POST'])
def login():
    error=None
    form= LoginForm(request.form)
    if request.method== 'POST':
        if form.validate_on_submit():
            user=User.query.filter_by(name=request.form['name']).first()
            if user is not None and bcrypt.check_password_hash(user.password, request.form['password']) :
                session['logged_in']= True
                session['company_id']=user.company
                session['name']=user.name
                flash('Welcome!')
                
                return redirect(url_for('main.main'))
            else:
                error= 'Invalid username, company name, or password.'
        else:
            error= 'All fields are required.'
    return render_template('login.html', form=form, error=error)

project/templates/QR_dataview.html
{% extends "_base.html" %}
{% block content %}


<div>
  <img src=https://media-exp1.licdn.com/dms/image/C4E0BAQH9ry_VPEPBPw/company-logo_200_200/0/1609696203090?e=1617840000&v=beta&t=zZvbSC0Zr3i8zwrTiRD5o6XwapPBs4lByvXKSOJi6ZA>

</div>

<div>
  <a href="{{ url_for('main.MaintenanceLogs', panel_id=panel_id) }}">
    <button type="button" class="btn btn-warning">Maintenance Logs</button>
  </a>

</div>

  <div class="container">
    <div class="row">
      <div class="col-12-xs">
        <h3>{{ panel_name }} Panel Documents</h3>
        
      </div>
        <h4> Email link to this page here</h4>
        <form method="post" action="{{ url_for('main.emailQRlink', panel_id=panel_id) }}">
          {{ form.csrf_token }}
          <div>
            {{ form.email.label }}
          </div>
          <div>
            {{ form.email }}
            <input type="submit" value="Send">
          </div>
        </form>
        
        
        &nbsp;
        &nbsp;
        <form class="upload-form" action="/QRupload/{{ panel_id }}/" method="post" enctype="multipart/form-data">
          <p><input type="file" name="file"></p>
          <button type="submit" name="Submit" class="btn btn-primary">Upload</button>

        </form>
        
        <table class="table table-striped">
          <tr>
            <th>Filename</th>
            <th></th>
          </tr>
        {% for f in files %}
        <tr>
          <td>{{f.key}}</td>
          <td>
            <form class="delete-form" action="{{ url_for('main.QRdelete', panel_id=panel_id) }}" method ="post">
              <input type="hidden" name="key" value= "{{ f.key }}">
              <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            </form>
            <br>
            <form class="download-form" action="{{ url_for('main.download', panel_id=panel_id) }}" method ="post">
              <input type="hidden" name="key" value= "{{ f.key }}">
              <button type="submit" class="btn btn-default btn-sm">Download</button>
            </form>
          </td>
        </tr>
        {% endfor %}
        </table>

      </div>
    </div>
  </div>
       

{% endblock %}

project/templates/QR_dataview_Emailed.html
{% extends "_base.html" %}
{% block content %}
<img src=https://media-exp1.licdn.com/dms/image/C4E0BAQH9ry_VPEPBPw/company-logo_200_200/0/1609696203090?e=1617840000&v=beta&t=zZvbSC0Zr3i8zwrTiRD5o6XwapPBs4lByvXKSOJi6ZA>
  <div class="container">
    <div class="row">
      <div class="col-12-xs">
        <h3>{{ panel_name }} Panel Documents</h3>
        
        &nbsp;
        &nbsp;
        <form class="upload-form" action="/QRlinkfupload/{{ panel_id }}/" method="post" enctype="multipart/form-data">
          <p><input type="file" name="file"></p>
          <button type="submit" name="Submit" class="btn btn-primary">Upload</button>

        </form>
        
        <table class="table table-striped">
          <tr>
            <th>Filename</th>
            <th></th>
          </tr>
        {% for f in files %}
        <tr>
          <td>{{f.key}}</td>
          <td>
            
            <form class="download-form" action="{{ url_for('main.download', panel_id=panel_id) }}" method ="post">
              <input type="hidden" name="key" value= "{{ f.key }}">
              <button type="submit" class="btn btn-default btn-sm">Download</button>
            </form>
          </td>
        </tr>
        {% endfor %}
        </table>

      </div>
    </div>
  </div>
       

{% endblock %}

project/templates/QR_login.html
{% extends "_base.html" %}
{% block content %}











{% endblock %}

project/templates/QR_register.html
{% extends "_base.html" %}
{% block content %}

<img src=https://media-exp1.licdn.com/dms/image/C4E0BAQH9ry_VPEPBPw/company-logo_200_200/0/1609696203090?e=1617840000&v=beta&t=zZvbSC0Zr3i8zwrTiRD5o6XwapPBs4lByvXKSOJi6ZA>
<h1>Please register QR code to link your data.</h1>
<form method="POST" action="">
  {{ form.csrf_token }}
  <div>
    {{ form.panel_name.label }}
  </div>
  <div>
    {{ form.panel_name}}
  </div>
  <div>
    {{ form.panel_id.label }}
  </div>
  <div>
    {{ form.panel_id }}
  </div>
  <div>
    {{ form.end_user.label }}
  </div>
  <div>
    {{ form.end_user}}
  </div>
  
  <div>
    <input type="submit" value="Register QR code"></p>
  </div>
</form>

  <br>

{% endblock %}

project/templates/_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Welcome to Scanmatics!</title>
    <!-- styles -->
    <link href="//maxcdn.bootstrapcdn.com/bootswatch/3.3.4/yeti/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/mainnn.css') }}">
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Scanmatics</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% if not session.logged_in %}
              <li><a href="/register">Signup</a></li>
            {% else %}
              <li><a href="/logout">Signout</a></li>
              
            {% endif %}
          </ul>
          {% if session.logged_in %}
          <ul class="nav navbar-nav navbar-right">
            <li><a>Welcome, {{username}}.</a></li>
            </ul>
            {% endif %}

        </div><!--/.nav-collapse -->
      </div>
    </div>
    
    <div class="container">
      <div class="content">

        {% for message in get_flashed_messages() %}
          <div class="alert alert-success">{{ message }}</div>
        {% endfor %}

        {% if error %}
          <div class="error"><strong>Error:</strong> {{ error }}</div>
        {% endif %}

        {% block content %}
        {% endblock %}

      </div>
      <!--div class="footer">
        <hr>
        <p>&copy; <a target="_blank" href="https://www.realpython.com">Real Python</a></p>
      </div-->
    </div><!-- /.container -->

    <!-- scripts -->
    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  </body>
</html>

project/templates/files.html
{% extends "_base.html" %}
{% block content %}
<div>
  <button type="submit" class="btn btn-default btn-sm"><a href="{{ url_for('main.panels',project_id=project_id) }}">Back</a></button>
</div>

<img src=https://media-exp1.licdn.com/dms/image/C4E0BAQH9ry_VPEPBPw/company-logo_200_200/0/1609696203090?e=1617840000&v=beta&t=zZvbSC0Zr3i8zwrTiRD5o6XwapPBs4lByvXKSOJi6ZA>
  <div class="container">
    <div class="row">
      <div class="col-12-xs">
        
        <h2>Panel name: {{ panel_name }}</h2>
        <h2>Panel ID: {{ panel_id }}</h2>
        <h2>Project ID: {{ project_id }}</h2>
        
        
        &nbsp;
        &nbsp;
        <form class="upload-form" action="/upload/{{ panel_id }}/" method="post" enctype="multipart/form-data">
          <p><input type="file" name="file"></p>
          <button type="submit" name="Submit" class="btn btn-primary">Upload</button>

        </form>
        
        <table class="table table-striped">
          <tr>
            <th>Filename</th>
            <th></th>
          </tr>
        {% for f in files %}
        <tr>
          <td>{{f.key}}</td>
          <td>
            <form class="delete-form" action="{{ url_for('main.delete', panel_id=panel_id) }}" method ="post">
              <input type="hidden" name="key" value= "{{ f.key }}">
              <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            </form>
            <br>
            <form class="download-form" action="{{ url_for('main.download', panel_id=panel_id) }}" method ="post">
              <input type="hidden" name="key" value= "{{ f.key }}">
              <button type="submit" class="btn btn-default btn-sm">Download</button>
            </form>
          </td>
        </tr>
        {% endfor %}
        </table>

      </div>
    </div>
  </div>




     
   
       

{% endblock %}

project/templates/login.html
{% extends "_base.html" %}
{% block content %}
<img src=https://media-exp1.licdn.com/dms/image/C4E0BAQH9ry_VPEPBPw/company-logo_200_200/0/1609696203090?e=1617840000&v=beta&t=zZvbSC0Zr3i8zwrTiRD5o6XwapPBs4lByvXKSOJi6ZA>
<h1>Please login to your Scanmatics account.</h1>

<form method="post" action="/">
    {{ form.csrf_token }}
    <div>
      {{ form.name.label }}
    </div>
    <div>
      {{ form.name }}
    </div>
    <div>
      {{ form.password.label }}
    </div>
    <div>
      {{ form.password}}
    </div>
    
    <div>
      <input type="submit" value="Submit">
    </div>
  </form>
  
  <br>
  
  <div class="">
    <em>Need an account? </em><a href="/register">Signup!</a>
  </div>
  <div class="">
    <a href="{{ url_for('main.reset_request')}}">Forgot password?</a>
  </div>
  
  

{% endblock %}

project/templates/main.html
{% extends "_base.html" %}
{% block content %}
<img src=https://media-exp1.licdn.com/dms/image/C4E0BAQH9ry_VPEPBPw/company-logo_200_200/0/1609696203090?e=1617840000&v=beta&t=zZvbSC0Zr3i8zwrTiRD5o6XwapPBs4lByvXKSOJi6ZA>
<h1>Welcome to your Scanmatics account.</h1>
<div class="add-customer">
  <h3>Add a new customer</h3>
  <table>
    <tr>
      <form action="{{ url_for('main.new_customer') }}" method="post">
        {{ form.csrf_token }}
        <td>
          <label>Customer Name:</label>
          <input name="name" type="text">
        </td>
        <td>
          &nbsp;
          &nbsp;
          <input class="button" type="submit" value="Save">
        </td>
      </form>
    </tr>
  </table>
</div>
<div class="customers">
  <br>
  <br>
  <h2>Customers:</h2>
  <div class="datagrid">
    <table class="table table-striped">
      <thead>
        <tr>
          <th width="300px"><strong>Customer Name</strong></th>
          <th><strong>Actions</strong></th>
        </tr>
      </thead>
      {% for customer in customers %}
        <tr>
          <td width="300px">{{ customer.name }}</td>
          <td>
            <a href="{{ url_for('main.projects', customer_id = customer.customer_id) }}">
              <button type="submit" class="btn btn-default btn-sm">Projects</button>
            </a>

            <a href="{{ url_for('main.delete_customer', customer_id = customer.customer_id) }}" class="text-white">
              <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            </a>

          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
  <br>
  <br>
</div>

{% endblock %}

project/templates/panels.html
{% extends "_base.html" %}
{% block content %}
<img src=https://media-exp1.licdn.com/dms/image/C4E0BAQH9ry_VPEPBPw/company-logo_200_200/0/1609696203090?e=1617840000&v=beta&t=zZvbSC0Zr3i8zwrTiRD5o6XwapPBs4lByvXKSOJi6ZA>
<h1>{{ project_name }} Panels</h1>

<div>
  <button type="submit" class="btn btn-default btn-sm"><a href="{{ url_for('main.projects',customer_id=panel_project_customer_id) }}">Back</a></button>
</div>
<div class="add-panel">
  <h3>Add a new panel to the project</h3>
  <table class="table table-striped">
    <tr>
      <form action="{{ url_for('main.new_panel', panel_project_id=panel_project_id) }}" method="post">
        {{ form.csrf_token }}
        <td>
          <label>Panel Name:</label>
          <input name="name" type="text">
          <input class="button" type="submit" value="Save">
        </td>
        
      </form>
    </tr>
  </table>
</div>
<div class="panels">
  <br>
  <br>
  <h2>Panels:</h2>
  <div class="datagrid">
    <table class="table table-striped">
      <thead>
        <tr>
          <th width="300px"><strong>Project</strong></th>
          <th><strong>Actions</strong></th>
        </tr>
      </thead>
      {% for panel in panels %}
        <tr>
          <td width="300px">{{ panel.name }}</td>
          <td>
            
            <a href="{{ url_for('main.files', panel_id=panel.panel_id) }}">
              <button type="submit" class="btn btn-default btn-sm">Documents</button>
            </a>

            <a href="{{ url_for('main.delete_panel', panel_id = panel.panel_id) }}" class="text-white">
              <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
  <br>
  <br>
</div>

{% endblock %}

project/templates/projects.html
{% extends "_base.html" %}
{% block content %}
<img src=https://media-exp1.licdn.com/dms/image/C4E0BAQH9ry_VPEPBPw/company-logo_200_200/0/1609696203090?e=1617840000&v=beta&t=zZvbSC0Zr3i8zwrTiRD5o6XwapPBs4lByvXKSOJi6ZA>
<h1>{{ customer_name }} Projects</h1>

<div>
  <button type="submit" class="btn btn-default btn-sm"><a href="{{ url_for('main.main') }}">Back</a></button>
</div>

<div class="add-project">
  <h3>Add a new project</h3>
  <table class="table table-striped">
    <tr>
      <form action="{{ url_for('main.new_project', project_customer_id=project_customer_id) }}" method="post">
        {{ form.csrf_token }}
        <td>
          <label>Project Name:</label>
          <input name="name" type="text">
          <input class="button" type="submit" value="Save">
        </td>
        
      </form>
    </tr>
  </table>
</div>
<div class="projects">
  <br>
  <br>
  <h2>Projects:</h2>
  <div class="datagrid">
    <table class="table table-striped">
      <thead>
        <tr>
          <th width="300px"><strong>Project</strong></th>
          <th><strong>Actions</strong></th>
        </tr>
      </thead>
      {% for project in projects %}
        <tr>
          <td width="300px">{{ project.name }}</td>
          <td>
            
            <a href="{{ url_for('main.panels', project_id = project.project_id) }}">
              <button type="submit" class="btn btn-default btn-sm">Panels</button>
            </a>

            <a href="{{ url_for('main.delete_project', project_id = project.project_id) }}" class="text-white">
              <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            </a>

          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
  <br>
  <br>
</div>

{% endblock %}

project/templates/reset_email.html
<p>
    To reset your password
    <a href="{{ url_for('main.reset_token', token=token, user=user, _external=True) }}">
        click here
    </a>.
</p>